// <auto-generated />
using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506000000_Phase6_EventBranding")]
    partial class Phase6_EventBranding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
