// <auto-generated />
using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505000000_Phase5_LeaguePlay")]
    partial class Phase5_LeaguePlay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
