// <auto-generated />
using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509000000_Phase7_TestMode")]
    partial class Phase7_TestMode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
