// <auto-generated />
using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508000000_SponsorChallengeDonationAmounts")]
    partial class SponsorChallengeDonationAmounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
