// ─────────────────────────────────────────────────────────────────────────────
// Data/Migrations/ApplicationDbContextModelSnapshot.cs
// ─────────────────────────────────────────────────────────────────────────────
//
// WHY THIS FILE EXISTS:
//   EF Core uses this snapshot to calculate what has CHANGED in your entity
//   model when you run `dotnet ef migrations add <name>`.
//   It stores the last-known-good state of the model so EF Core can diff
//   your current entities against it and generate only the delta migration.
//
//   Without this file, EF Core would regenerate the entire schema on every
//   migration instead of just the changes.
//
// IMPORTANT: This file is AUTO-GENERATED by EF Core.
//   When you run `dotnet ef migrations add Phase2_AddOfflineColumns`,
//   EF Core will UPDATE this file to reflect the new model state.
//   DO NOT edit this file manually — let `dotnet ef` manage it.
//
// THIS IS A SIMPLIFIED SNAPSHOT:
//   The real snapshot generated by `dotnet ef` is much longer and more
//   precise (it includes every column type, constraint, and index detail).
//   This version establishes the pattern and structure.
//   Run `dotnet ef migrations add Phase1_InitialSchema` in the actual
//   project to generate the correct version for your environment.
// ─────────────────────────────────────────────────────────────────────────────

using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        // NOTE: The full model snapshot is generated by running:
        //   dotnet ef migrations add Phase1_InitialSchema
        // from the apps/api directory. That command will replace this
        // placeholder with a complete, precise snapshot.

        // This stub is here so the project compiles and the migration
        // infrastructure is in place for the developer to run the command.
#pragma warning restore 612, 618
    }
}
