// <auto-generated />
using System;
using GolfFundraiserPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GolfFundraiserPro.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GolfFundraiserPro.Api.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrgId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.ChallengeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ResultNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result_notes");

                    b.Property<float?>("ResultValue")
                        .HasColumnType("real")
                        .HasColumnName("result_value");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("TeamId");

                    b.ToTable("challenge_results");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.CourseHole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<float?>("CupElevationM")
                        .HasColumnType("real")
                        .HasColumnName("cup_elevation_m");

                    b.Property<Point>("CupLocation")
                        .HasColumnType("geography (pointz)")
                        .HasColumnName("cup_location");

                    b.Property<short>("HandicapIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("handicap_index");

                    b.Property<short>("HoleNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_number");

                    b.Property<short>("Par")
                        .HasColumnType("smallint")
                        .HasColumnName("par");

                    b.Property<int?>("YardageBlue")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_blue");

                    b.Property<int?>("YardageRed")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_red");

                    b.Property<int?>("YardageWhite")
                        .HasColumnType("integer")
                        .HasColumnName("yardage_white");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_holes");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DonorEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("donor_email");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("donor_name");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("ReceiptSent")
                        .HasColumnType("boolean")
                        .HasColumnName("receipt_sent");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("email_templates");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("event_code");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<short>("Holes")
                        .HasColumnType("smallint")
                        .HasColumnName("holes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("Is501c3")
                        .HasColumnType("boolean")
                        .HasColumnName("is_501c3");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MissionStatement")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mission_statement");

                    b.Property<string>("ThemeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("theme_json");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EventCode")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.HoleChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("challenge_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<short?>("HoleNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_number");

                    b.Property<string>("PrizeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("prize_description");

                    b.Property<Guid?>("SponsorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsor_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SponsorId");

                    b.ToTable("hole_challenges");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Is501c3")
                        .HasColumnType("boolean")
                        .HasColumnName("is_501c3");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("MissionStatement")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mission_statement");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("ThemeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Is501c3 = true,
                            MissionStatement = "Supporting excellence in Clear Lake High School extracurricular programs.",
                            Name = "Clear Lake High School Boosters",
                            Slug = "clhs"
                        });
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgeGroup")
                        .HasColumnType("text")
                        .HasColumnName("age_group");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_in_status");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<double?>("HandicapIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("handicap_index");

                    b.Property<bool>("HasPaymentMethod")
                        .HasColumnType("boolean")
                        .HasColumnName("has_payment_method");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PairingNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pairing_note");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_type");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("text")
                        .HasColumnName("skill_level");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("ExpoPushToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("expo_push_token");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("EventId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_players_event_id_email_unique");

                    b.ToTable("players");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("QrType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_type");

                    b.Property<string>("SvgData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("svg_data");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("qr_codes");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("BallLocation")
                        .HasColumnType("geography (point)")
                        .HasColumnName("ball_location");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<Point>("DriveLocation")
                        .HasColumnType("geography (point)")
                        .HasColumnName("drive_location");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<short>("GrossScore")
                        .HasColumnType("smallint")
                        .HasColumnName("gross_score");

                    b.Property<short>("HoleNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_number");

                    b.Property<bool>("IsConflicted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_conflicted");

                    b.Property<string>("PlayerShotsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("player_shots");

                    b.Property<short?>("Putts")
                        .HasColumnType("smallint")
                        .HasColumnName("putts");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_scores_event_id");

                    b.HasIndex("TeamId", "HoleNumber")
                        .HasDatabaseName("IX_scores_team_id_hole_number");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PlacementsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("placements");

                    b.Property<string>("Tagline")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tagline");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("sponsors");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CaptainPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("captain_player_id");

                    b.Property<string>("CheckInStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_in_status");

                    b.Property<bool>("EntryFeePaid")
                        .HasColumnType("boolean")
                        .HasColumnName("entry_fee_paid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_expires_at");

                    b.Property<string>("InviteToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("invite_token");

                    b.Property<short>("MaxPlayers")
                        .HasColumnType("smallint")
                        .HasColumnName("max_players");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short?>("StartingHole")
                        .HasColumnType("smallint")
                        .HasColumnName("starting_hole");

                    b.Property<DateTime?>("TeeTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tee_time");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuctionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auction_type");

                    b.Property<int>("BidIncrementCents")
                        .HasColumnType("integer")
                        .HasColumnName("bid_increment_cents");

                    b.Property<int?>("BuyNowPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("buy_now_price_cents");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentHighBidCents")
                        .HasColumnType("integer")
                        .HasColumnName("current_high_bid_cents");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("DonationDenominationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("donation_denominations");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("FairMarketValueCents")
                        .HasColumnType("integer")
                        .HasColumnName("fair_market_value_cents");

                    b.Property<int?>("GoalCents")
                        .HasColumnType("integer")
                        .HasColumnName("goal_cents");

                    b.Property<int>("MaxExtensionMin")
                        .HasColumnType("integer")
                        .HasColumnName("max_extension_min");

                    b.Property<int?>("MinimumBidCents")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_bid_cents");

                    b.Property<DateTime?>("OriginalClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_closes_at");

                    b.Property<string>("PhotoUrlsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("photo_urls");

                    b.Property<int>("StartingBidCents")
                        .HasColumnType("integer")
                        .HasColumnName("starting_bid_cents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_auction_items_event_id");

                    b.ToTable("auction_items");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentCalledAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("current_called_amount_cents");

                    b.Property<Guid?>("CurrentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_item_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_auction_sessions_event_id");

                    b.HasIndex("CurrentItemId");

                    b.ToTable("auction_sessions");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionWinner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_item_id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<string>("ChargeStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("charge_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<bool>("ReceiptSent")
                        .HasColumnType("boolean")
                        .HasColumnName("receipt_sent");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemId")
                        .HasDatabaseName("IX_auction_winners_auction_item_id");

                    b.HasIndex("PlayerId");

                    b.ToTable("auction_winners");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("AuctionItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_item_id");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemId")
                        .HasDatabaseName("IX_bids_auction_item_id");

                    b.HasIndex("PlayerId");

                    b.ToTable("bids");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.StripeCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("card_brand");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("card_last4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripePaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stripe_payment_method_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_stripe_customers_player_id_unique");

                    b.ToTable("stripe_customers");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DuesCents")
                        .HasColumnType("integer")
                        .HasColumnName("dues_cents");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<double>("HandicapCap")
                        .HasColumnType("double precision")
                        .HasColumnName("handicap_cap");

                    b.Property<string>("HandicapFormulaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("handicap_formula");

                    b.Property<string>("HandicapSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handicap_system");

                    b.Property<short>("MaxFlights")
                        .HasColumnType("smallint")
                        .HasColumnName("max_flights");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("leagues");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("RoundsCounted")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds_counted");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StandingMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("standing_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<short>("TotalRounds")
                        .HasColumnType("smallint")
                        .HasColumnName("total_rounds");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("IX_seasons_league_id");

                    b.ToTable("seasons");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("MaxHandicap")
                        .HasColumnType("double precision")
                        .HasColumnName("max_handicap");

                    b.Property<double?>("MinHandicap")
                        .HasColumnType("double precision")
                        .HasColumnName("min_handicap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Absences")
                        .HasColumnType("smallint")
                        .HasColumnName("absences");

                    b.Property<bool>("DuesPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("dues_paid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<double>("HandicapIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("handicap_index");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<short>("RoundsPlayed")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds_played");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_league_members_season_id_email_unique");

                    b.ToTable("league_members");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("RoundDate")
                        .HasColumnType("date")
                        .HasColumnName("round_date");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_league_rounds_season_id");

                    b.ToTable("league_rounds");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeaguePairing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("GroupNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("group_number");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<string>("MemberIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("member_ids");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<short?>("StartingHole")
                        .HasColumnType("smallint")
                        .HasColumnName("starting_hole");

                    b.Property<TimeOnly?>("TeeTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("tee_time");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("IX_league_pairings_round_id");

                    b.ToTable("league_pairings");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("GrossScore")
                        .HasColumnType("smallint")
                        .HasColumnName("gross_score");

                    b.Property<short>("HoleNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_number");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<short>("NetScore")
                        .HasColumnType("smallint")
                        .HasColumnName("net_score");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<short>("StablefordPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("stableford_points");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "MemberId")
                        .HasDatabaseName("IX_league_scores_round_member");

                    b.ToTable("league_scores");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.HandicapHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AdminOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("admin_override");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Differential")
                        .HasColumnType("double precision")
                        .HasColumnName("differential");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<double>("NewIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("new_index");

                    b.Property<double>("OldIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("old_index");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_handicap_history_member_id");

                    b.ToTable("handicap_history");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("flight_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("NetStrokes")
                        .HasColumnType("integer")
                        .HasColumnName("net_strokes");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint")
                        .HasColumnName("rank");

                    b.Property<short>("RoundsPlayed")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds_played");

                    b.Property<double>("SeasonAvgNet")
                        .HasColumnType("double precision")
                        .HasColumnName("season_avg_net");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_standings_season_member_unique");

                    b.ToTable("standings");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Skin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("CarriedOverFromHole")
                        .HasColumnType("smallint")
                        .HasColumnName("carried_over_from_hole");

                    b.Property<short>("HoleNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("hole_number");

                    b.Property<int>("PotCents")
                        .HasColumnType("integer")
                        .HasColumnName("pot_cents");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<Guid?>("WinnerMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_member_id");

                    b.HasKey("Id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("IX_skins_round_id");

                    b.ToTable("skins");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Features.Auth.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Data.ApplicationUser", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.ChallengeResult", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.HoleChallenge", "Challenge")
                        .WithMany("Results")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Course", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Courses")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.CourseHole", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Course", "Course")
                        .WithMany("Holes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Donation", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("Donations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.EmailTemplate", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Event", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.HoleChallenge", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("HoleChallenges")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Player", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.QrCode", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("QrCodes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Score", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("Scores")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Team", "Team")
                        .WithMany("Scores")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Sponsor", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("Sponsors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Team", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany("Teams")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionSession", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", "CurrentItem")
                        .WithMany()
                        .HasForeignKey("CurrentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("CurrentItem");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionWinner", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", "AuctionItem")
                        .WithMany("Winners")
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionItem");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Bid", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", "AuctionItem")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionItem");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.StripeCustomer", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Features.Auth.RefreshTokenRecord", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.League", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Season", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Flight", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Season", "Season")
                        .WithMany("Flights")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Flight", "Flight")
                        .WithMany("Members")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Season", "Season")
                        .WithMany("Members")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeaguePairing", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", "Round")
                        .WithMany("Pairings")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueScore", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", "Member")
                        .WithMany("Scores")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", "Round")
                        .WithMany("Scores")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.HandicapHistory", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", "Member")
                        .WithMany("HandicapHistories")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Standing", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Member");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Skin", b =>
                {
                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", "Round")
                        .WithMany("Skins")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Round");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.AuctionItem", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Winners");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Course", b =>
                {
                    b.Navigation("Holes");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Event", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("HoleChallenges");

                    b.Navigation("QrCodes");

                    b.Navigation("Scores");

                    b.Navigation("Sponsors");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.HoleChallenge", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.League", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Season", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("Members");

                    b.Navigation("Rounds");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Flight", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueMember", b =>
                {
                    b.Navigation("HandicapHistories");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.LeagueRound", b =>
                {
                    b.Navigation("Pairings");

                    b.Navigation("Scores");

                    b.Navigation("Skins");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("EmailTemplates");

                    b.Navigation("Events");

                    b.Navigation("Leagues");
                });

            modelBuilder.Entity("GolfFundraiserPro.Api.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
