// ─────────────────────────────────────────────────────────────────────────────
// Domain/Entities/AllEntities.cs — EF Core Entity Classes (Phase 1 Schema)
// ─────────────────────────────────────────────────────────────────────────────
//
// WHY ALL ENTITIES IN ONE FILE FOR NOW:
//   Phase 1 has 12 entity classes. Splitting them across files adds navigation
//   overhead. Once the team grows, split into one file per entity. For now,
//   keeping them together makes the spec → code mapping easier to verify.
//
// EF CORE CONVENTIONS USED:
//   • Id property named "Id" → EF Core recognizes it as the primary key
//   • Navigation properties marked as virtual → enables lazy loading if needed
//   • Required strings use string (not string?) — nullable reference types are enabled
//   • Nullable columns use string? / DateTime? / int? etc.
//   • [Column] attributes override EF Core's default snake_case conversion
//
// UUID GENERATION STRATEGY (spec Foundation §4.1):
//   "All tables use UUID primary keys generated by the API (not DB serial)"
//   Ids are set in the API code before inserting, using Guid.NewGuid().
//   EF Core is told NOT to use database-generated values via:
//     builder.Property(e => e.Id).ValueGeneratedNever()
//   This is configured in ApplicationDbContext.OnModelCreating().
//
// FUTURE PHASE COLUMNS (spec Foundation §4):
//   "Columns populated in later phases are nullable until that phase is deployed."
//   Phase 4 columns (stripe_customer_id, has_payment_method) are included
//   as nullable properties so the schema is complete from Day 1. This prevents
//   breaking migrations when Phase 4 ships.
// ─────────────────────────────────────────────────────────────────────────────

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;
using GolfFundraiserPro.Api.Domain.Enums;

namespace GolfFundraiserPro.Api.Domain.Entities;

// ─────────────────────────────────────────────────────────────────────────────
// ORGANIZATION
// Maps to the "organizations" table — the top-level tenant entity.
// Every event, course, and email template belongs to an organization.
// ─────────────────────────────────────────────────────────────────────────────
[Table("organizations")]
public class Organization
{
    /// <summary>
    /// UUID primary key. Generated by the API before insert (not by the database).
    /// See spec: "All tables use UUID primary keys generated by the API (not DB serial)."
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>Display name of the organization. e.g. "Clear Lake High School Boosters"</summary>
    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// URL-safe identifier. e.g. "clhs". Used in public routes: /e/{slug}/{eventCode}.
    /// Max 60 chars. Must be unique across all organizations.
    /// </summary>
    [Column("slug")]
    [MaxLength(60)]
    public string Slug { get; set; } = string.Empty;

    /// <summary>CDN URL of the org's logo image. Uploaded via POST /api/v1/orgs/{id}/logo.</summary>
    [Column("logo_url")]
    [MaxLength(500)]
    public string? LogoUrl { get; set; }

    /// <summary>
    /// 5-token color theme stored as JSONB.
    /// Stored as a JSON string and deserialized by the API.
    /// null = use ECO_GREEN_DEFAULT (handled in the theme service layer).
    /// EF Core maps this as a string column with HasColumnType("jsonb").
    /// </summary>
    [Column("theme", TypeName = "jsonb")]
    public string? ThemeJson { get; set; }

    /// <summary>The org's charitable mission statement. Displayed on donation pages.</summary>
    [Column("mission_statement")]
    [MaxLength(1000)]
    public string? MissionStatement { get; set; }

    /// <summary>
    /// If true, donation receipt emails include the IRS 501(c)3 tax deductibility notice.
    /// Spec: "Donation receipt emails: amount, event name, org name, 501c3 note if is_501c3=true."
    /// </summary>
    [Column("is_501c3")]
    public bool Is501c3 { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    public ICollection<Event> Events { get; set; } = new List<Event>();
    public ICollection<Course> Courses { get; set; } = new List<Course>();
    public ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();
}

// ─────────────────────────────────────────────────────────────────────────────
// EVENT
// Maps to the "events" table. The central scheduling entity.
// ─────────────────────────────────────────────────────────────────────────────
[Table("events")]
public class Event
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// 8-character random alphanumeric code. Used in QR codes and public URLs.
    /// e.g. "A3B7C9D2" → /e/clhs/A3B7C9D2
    /// Generated by the API on event creation. Indexed for fast lookup by QR scanner.
    /// </summary>
    [Column("event_code")]
    [MaxLength(8)]
    public string EventCode { get; set; } = string.Empty;

    [Column("format")]
    public EventFormat Format { get; set; }

    [Column("start_type")]
    public EventStartType StartType { get; set; }

    /// <summary>Number of holes: 9 or 18. All scoring calculations respect this value.</summary>
    [Column("holes")]
    public short Holes { get; set; } = 18;

    [Column("status")]
    public EventStatus Status { get; set; } = EventStatus.Draft;

    /// <summary>
    /// Scheduled round start time in UTC. Used to trigger the 24-hour reminder email.
    /// Nullable because Draft events may not have a confirmed start time yet.
    /// </summary>
    [Column("start_at")]
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Flexible JSONB settings bag: allow_walk_ups, max_teams, tee_intervals,
    /// free_agent_enabled, theme_override, etc.
    /// Stored as JSON string, deserialized in the Events feature service.
    /// </summary>
    [Column("config", TypeName = "jsonb")]
    public string ConfigJson { get; set; } = "{}";

    // Foreign key + navigation
    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;

    public ICollection<Team> Teams { get; set; } = new List<Team>();
    public ICollection<Score> Scores { get; set; } = new List<Score>();
    public ICollection<Sponsor> Sponsors { get; set; } = new List<Sponsor>();
    public ICollection<HoleChallenge> HoleChallenges { get; set; } = new List<HoleChallenge>();
    public ICollection<Donation> Donations { get; set; } = new List<Donation>();
    public ICollection<QrCode> QrCodes { get; set; } = new List<QrCode>();

    /// <summary>
    /// The course attached to this event (set via POST /api/v1/events/{id}/course).
    /// Optional — events can be created before a course is attached.
    /// </summary>
    public Course? Course { get; set; }

    [Column("course_id")]
    public Guid? CourseId { get; set; }
}

// ─────────────────────────────────────────────────────────────────────────────
// COURSE
// Maps to the "courses" table. A golf course with per-hole metadata.
// ─────────────────────────────────────────────────────────────────────────────
[Table("courses")]
public class Course
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("address")]
    [MaxLength(300)]
    public string Address { get; set; } = string.Empty;

    [Column("city")]
    [MaxLength(100)]
    public string City { get; set; } = string.Empty;

    [Column("state")]
    [MaxLength(50)]
    public string State { get; set; } = string.Empty;

    [Column("zip")]
    [MaxLength(20)]
    public string Zip { get; set; } = string.Empty;

    /// <summary>
    /// WGS-84 lat/lon of the course clubhouse / main entrance.
    /// Type: GEOGRAPHY(Point,4326) in PostgreSQL.
    /// Requires NetTopologySuite + UseNetTopologySuite() on NpgsqlDataSource.
    /// SRID 4326 = standard GPS coordinate system.
    /// </summary>
    [Column("location", TypeName = "geography (point)")]
    public Point? Location { get; set; }

    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;

    public ICollection<CourseHole> Holes { get; set; } = new List<CourseHole>();
}

// ─────────────────────────────────────────────────────────────────────────────
// COURSE HOLE
// Maps to the "course_holes" table. One row per hole per course (up to 18).
// ─────────────────────────────────────────────────────────────────────────────
[Table("course_holes")]
public class CourseHole
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("course_id")]
    public Guid CourseId { get; set; }

    /// <summary>Hole number 1–18 (or 1–9 for 9-hole courses).</summary>
    [Column("hole_number")]
    public short HoleNumber { get; set; }

    /// <summary>Par for this hole (3, 4, or 5).</summary>
    [Column("par")]
    public short Par { get; set; }

    /// <summary>
    /// Hole difficulty rank 1–18 (1 = hardest hole on the course).
    /// Used to allocate net strokes in match play and Phase 5 league net scoring.
    /// The hardest hole gets handicap strokes first when players have a handicap.
    /// </summary>
    [Column("handicap_index")]
    public short HandicapIndex { get; set; }

    // Yardages from different tee boxes (nullable — not all courses provide all tees)
    [Column("yardage_white")]
    public int? YardageWhite { get; set; }

    [Column("yardage_blue")]
    public int? YardageBlue { get; set; }

    [Column("yardage_red")]
    public int? YardageRed { get; set; }

    /// <summary>
    /// Phase 6: GPS location of the pin (cup) on the green.
    /// Type: GEOGRAPHY(PointZ,4326) — includes elevation (Z coordinate).
    /// NULL until Phase 6 is deployed. The column exists in the schema from Phase 1
    /// per the spec: "Columns populated in later phases are nullable."
    /// </summary>
    [Column("cup_location", TypeName = "geography (pointz)")]
    public Point? CupLocation { get; set; }

    /// <summary>Phase 6: Elevation of the cup in meters above sea level.</summary>
    [Column("cup_elevation_m")]
    public float? CupElevationM { get; set; }

    [ForeignKey(nameof(CourseId))]
    public Course Course { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// TEAM
// Maps to the "teams" table. A group of players registered for an event.
// ─────────────────────────────────────────────────────────────────────────────
[Table("teams")]
public class Team
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The player who registered the team. May be null for admin-created teams.
    /// NOT a FK to the users table — it's a FK to players in this same event.
    /// </summary>
    [Column("captain_player_id")]
    public Guid? CaptainPlayerId { get; set; }

    /// <summary>
    /// For shotgun starts: which hole number this team begins on (1–18).
    /// Set by POST /api/v1/events/{id}/shotgun-assignments.
    /// </summary>
    [Column("starting_hole")]
    public short? StartingHole { get; set; }

    /// <summary>
    /// For tee_times start type: the team's scheduled tee time in UTC.
    /// Set by POST /api/v1/events/{id}/tee-times.
    /// </summary>
    [Column("tee_time")]
    public DateTime? TeeTime { get; set; }

    /// <summary>Whether the entry fee has been collected for this team.</summary>
    [Column("entry_fee_paid")]
    public bool EntryFeePaid { get; set; }

    /// <summary>
    /// Signed HMAC token for the team invite link.
    /// Format: base64url(HMAC-SHA256(teamId + expires_at, JWT_SECRET))
    /// Expires after 48 hours (invite_expires_at).
    /// </summary>
    [Column("invite_token")]
    [MaxLength(128)]
    public string? InviteToken { get; set; }

    [Column("invite_expires_at")]
    public DateTime? InviteExpiresAt { get; set; }

    /// <summary>Maximum number of players allowed on this team. Default: 4.</summary>
    [Column("max_players")]
    public short MaxPlayers { get; set; } = 4;

    [Column("check_in_status")]
    public CheckInStatus CheckInStatus { get; set; } = CheckInStatus.Pending;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    public ICollection<Player> Players { get; set; } = new List<Player>();
    public ICollection<Score> Scores { get; set; } = new List<Score>();
}

// ─────────────────────────────────────────────────────────────────────────────
// PLAYER
// Maps to the "players" table. An individual golfer registered for an event.
// Note: a player is event-scoped (not a global user account).
//       The organizer has a user account (ASP.NET Identity); golfers do not.
// ─────────────────────────────────────────────────────────────────────────────
[Table("players")]
public class Player
{
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// The team this player belongs to.
    /// Nullable because free agents are in the DB before being assigned a team.
    /// </summary>
    [Column("team_id")]
    public Guid? TeamId { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("first_name")]
    [MaxLength(100)]
    public string FirstName { get; set; } = string.Empty;

    [Column("last_name")]
    [MaxLength(100)]
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Email is unique per event (a person can't register twice for the same event).
    /// The DB has a UNIQUE constraint on (event_id, email).
    /// This is configured in ApplicationDbContext.OnModelCreating().
    /// </summary>
    [Column("email")]
    [MaxLength(254)]
    public string Email { get; set; } = string.Empty;

    [Column("phone")]
    [MaxLength(30)]
    public string? Phone { get; set; }

    /// <summary>
    /// Golf handicap index (USGA format). e.g. 14.2 means 14.2 handicap.
    /// Used by Phase 5 league net scoring and the free agent auto-pair algorithm.
    /// Nullable because most charity event golfers don't have official handicaps.
    /// </summary>
    [Column("handicap_index")]
    public double? HandicapIndex { get; set; }

    [Column("registration_type")]
    public RegistrationType RegistrationType { get; set; }

    /// <summary>Self-reported for free agent pool matching. Nullable.</summary>
    [Column("skill_level")]
    public SkillLevel? SkillLevel { get; set; }

    /// <summary>Self-reported for free agent pool matching. Nullable.</summary>
    [Column("age_group")]
    public AgeGroup? AgeGroup { get; set; }

    /// <summary>
    /// Free-text pairing note from the player during free agent registration.
    /// e.g. "I know the Smith family, please pair me with them if possible."
    /// The organizer sees this on the Free Agent Board.
    /// </summary>
    [Column("pairing_note")]
    [MaxLength(500)]
    public string? PairingNote { get; set; }

    [Column("check_in_status")]
    public CheckInStatus CheckInStatus { get; set; } = CheckInStatus.Pending;

    [Column("check_in_at")]
    public DateTime? CheckInAt { get; set; }

    // ── Phase 4 columns ──────────────────────────────────────────────────────
    // These columns exist in the schema from Phase 1 (nullable) but are only
    // populated once Phase 4 (Stripe payments) is deployed.

    /// <summary>
    /// Phase 4: true once the player has saved a card via Stripe SetupIntent.
    /// Controls whether auction bidding is available to this player.
    /// </summary>
    [Column("has_payment_method")]
    public bool HasPaymentMethod { get; set; } = false;

    /// <summary>
    /// Phase 4: Stripe Customer ID (cus_...) for this player.
    /// Stored here as a denormalized lookup; canonical record is stripe_customers table.
    /// </summary>
    [Column("stripe_customer_id")]
    [MaxLength(50)]
    public string? StripeCustomerId { get; set; }

    /// <summary>
    /// Phase 3: Expo push notification token registered from the mobile app.
    /// Null = player has not granted permission or has opted out.
    /// </summary>
    [Column("expo_push_token")]
    [MaxLength(500)]
    public string? ExpoPushToken { get; set; }

    // Navigation
    [ForeignKey(nameof(TeamId))]
    public Team? Team { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// SCORE
// Maps to the "scores" table. One row per hole per team.
// The leaderboard is computed by aggregating these rows.
// ─────────────────────────────────────────────────────────────────────────────
[Table("scores")]
public class Score
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("team_id")]
    public Guid TeamId { get; set; }

    /// <summary>Which hole (1–18) this score is for.</summary>
    [Column("hole_number")]
    public short HoleNumber { get; set; }

    /// <summary>
    /// Total strokes for this team on this hole (gross score).
    /// In scramble format, this is the team's collective score.
    /// In stroke/best_ball, this is the relevant individual score.
    /// </summary>
    [Column("gross_score")]
    public short GrossScore { get; set; }

    /// <summary>Number of putts on the green. Optional — used for putting challenges.</summary>
    [Column("putts")]
    public short? Putts { get; set; }

    /// <summary>
    /// Phase 2: Per-player shot breakdown. Stored as JSONB.
    /// e.g. { "player-uuid-1": 4, "player-uuid-2": 5 }
    /// Null in Phase 1 (admin entry doesn't record individual shots).
    /// </summary>
    [Column("player_shots", TypeName = "jsonb")]
    public string? PlayerShotsJson { get; set; }

    /// <summary>
    /// The device that submitted this score. Used for conflict detection.
    /// If two different device IDs submit different scores for the same hole,
    /// is_conflicted is set to true and the admin must resolve it.
    /// </summary>
    [Column("device_id")]
    [MaxLength(100)]
    public string DeviceId { get; set; } = string.Empty;

    [Column("submitted_at")]
    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this score was synced from the mobile device to the server.
    /// Null for scores entered directly on the admin dashboard (no sync needed).
    /// </summary>
    [Column("synced_at")]
    public DateTime? SyncedAt { get; set; }

    [Column("source")]
    public ScoreSource Source { get; set; }

    /// <summary>
    /// True if two devices submitted conflicting scores for this hole.
    /// The admin dashboard shows a conflict resolution UI when this is true.
    /// </summary>
    [Column("is_conflicted")]
    public bool IsConflicted { get; set; } = false;

    // ── Phase 6 GPS columns ──────────────────────────────────────────────────
    /// <summary>Phase 6: GPS location where the team's drive landed.</summary>
    [Column("drive_location", TypeName = "geography (point)")]
    public Point? DriveLocation { get; set; }

    /// <summary>Phase 6: GPS location of the ball when it came to rest.</summary>
    [Column("ball_location", TypeName = "geography (point)")]
    public Point? BallLocation { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    [ForeignKey(nameof(TeamId))]
    public Team Team { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// SPONSOR
// Maps to the "sponsors" table. Sponsors are attached to events.
// ─────────────────────────────────────────────────────────────────────────────
[Table("sponsors")]
public class Sponsor
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("logo_url")]
    [MaxLength(500)]
    public string LogoUrl { get; set; } = string.Empty;

    [Column("website_url")]
    [MaxLength(500)]
    public string? WebsiteUrl { get; set; }

    [Column("tagline")]
    [MaxLength(200)]
    public string? Tagline { get; set; }

    [Column("tier")]
    public SponsorTier Tier { get; set; }

    /// <summary>
    /// JSONB placement configuration. e.g.:
    /// { "leaderboard": true, "landingPage": true, "holeNumbers": [7, 14] }
    /// The Sponsors feature service deserializes this to a typed object.
    /// </summary>
    [Column("placements", TypeName = "jsonb")]
    public string PlacementsJson { get; set; } = "{}";

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// HOLE CHALLENGE
// Maps to the "hole_challenges" table. On-course contests.
// ─────────────────────────────────────────────────────────────────────────────
[Table("hole_challenges")]
public class HoleChallenge
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    /// <summary>
    /// Which hole this challenge is on. NULL = all-day challenge (e.g. hole-in-one
    /// on any hole throughout the round).
    /// </summary>
    [Column("hole_number")]
    public short? HoleNumber { get; set; }

    [Column("challenge_type")]
    public ChallengeType ChallengeType { get; set; }

    [Column("description")]
    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    [Column("prize_description")]
    [MaxLength(500)]
    public string? PrizeDescription { get; set; }

    /// <summary>Optional: the sponsor funding this challenge's prize.</summary>
    [Column("sponsor_id")]
    public Guid? SponsorId { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    [ForeignKey(nameof(SponsorId))]
    public Sponsor? Sponsor { get; set; }

    public ICollection<ChallengeResult> Results { get; set; } = new List<ChallengeResult>();
}

// ─────────────────────────────────────────────────────────────────────────────
// CHALLENGE RESULT
// Maps to the "challenge_results" table. Admin records results here.
// ─────────────────────────────────────────────────────────────────────────────
[Table("challenge_results")]
public class ChallengeResult
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("challenge_id")]
    public Guid ChallengeId { get; set; }

    [Column("team_id")]
    public Guid TeamId { get; set; }

    /// <summary>Which player on the team achieved this result (optional for team challenges).</summary>
    [Column("player_id")]
    public Guid? PlayerId { get; set; }

    /// <summary>
    /// Numeric result value. Semantics depend on challenge_type:
    ///   closest_to_pin / longest_drive → distance in yards (lower/higher wins respectively)
    ///   putting → number of putts (lower wins)
    ///   Phase 6: GPS-measured distance replaces manual entry
    /// </summary>
    [Column("result_value")]
    public float? ResultValue { get; set; }

    [Column("result_notes")]
    [MaxLength(500)]
    public string? ResultNotes { get; set; }

    [Column("recorded_at")]
    public DateTime RecordedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(ChallengeId))]
    public HoleChallenge Challenge { get; set; } = null!;

    [ForeignKey(nameof(TeamId))]
    public Team Team { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// DONATION
// Maps to the "donations" table.
// ─────────────────────────────────────────────────────────────────────────────
[Table("donations")]
public class Donation
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("donor_name")]
    [MaxLength(200)]
    public string DonorName { get; set; } = string.Empty;

    [Column("donor_email")]
    [MaxLength(254)]
    public string DonorEmail { get; set; } = string.Empty;

    /// <summary>
    /// Amount in US cents (integer) to avoid floating-point currency errors.
    /// e.g. $50.00 is stored as 5000.
    /// All money values in the system follow this convention.
    /// </summary>
    [Column("amount_cents")]
    public int AmountCents { get; set; }

    /// <summary>Whether a donation receipt email has been sent to this donor.</summary>
    [Column("receipt_sent")]
    public bool ReceiptSent { get; set; } = false;

    /// <summary>
    /// Phase 4: Stripe PaymentIntent ID for online donations processed via the donation widget.
    /// Null for Phase 1 (donations are recorded manually by the organizer).
    /// </summary>
    [Column("stripe_payment_intent_id")]
    [MaxLength(100)]
    public string? StripePaymentIntentId { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// EMAIL TEMPLATE
// Maps to the "email_templates" table.
// Templates are org-branded and stored in the database (not as static files).
// This allows organizers to customise email copy in the admin dashboard.
// ─────────────────────────────────────────────────────────────────────────────
[Table("email_templates")]
public class EmailTemplate
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("trigger_type")]
    public EmailTriggerType TriggerType { get; set; }

    [Column("subject")]
    [MaxLength(200)]
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Full HTML email body with theme placeholders like {{PRIMARY_COLOR}}.
    /// At send time, buildEmailVars() from @gfp/theme substitutes the org's
    /// actual hex values. The QR code and player-specific data are injected
    /// by the Email feature service at send time.
    /// </summary>
    [Column("html_body")]
    public string HtmlBody { get; set; } = string.Empty;

    /// <summary>
    /// If false, this template is disabled — the trigger fires but no email is sent.
    /// Allows orgs to opt out of specific automated emails (e.g. disable reminder emails).
    /// </summary>
    [Column("is_active")]
    public bool IsActive { get; set; } = true;

    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// QR CODE
// Maps to the "qr_codes" table.
// Pre-generated QR codes for an event (included in the Print Kit PDF).
// ─────────────────────────────────────────────────────────────────────────────
[Table("qr_codes")]
public class QrCode
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("qr_type")]
    public QrType QrType { get; set; }

    /// <summary>
    /// Signed token encoded in the QR. Format depends on qr_type:
    ///   player_checkin → HMAC-signed JSON { type, player_id, event_id }
    ///   event_join     → just the event_code (public, no signature needed)
    ///   donation        → just the event_code
    /// Max 128 chars — QR codes degrade in density above this.
    /// </summary>
    [Column("token")]
    [MaxLength(128)]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// SVG string of the rendered QR code image.
    /// Stored in the DB so the Print Kit PDF can be generated without
    /// re-rendering QR codes on every download.
    /// </summary>
    [Column("svg_data")]
    public string SvgData { get; set; } = string.Empty;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}
