// ─────────────────────────────────────────────────────────────────────────────
// Domain/Entities/AllEntities.cs — EF Core Entity Classes (Phase 1 Schema)
// ─────────────────────────────────────────────────────────────────────────────
//
// WHY ALL ENTITIES IN ONE FILE FOR NOW:
//   Phase 1 has 12 entity classes. Splitting them across files adds navigation
//   overhead. Once the team grows, split into one file per entity. For now,
//   keeping them together makes the spec → code mapping easier to verify.
//
// EF CORE CONVENTIONS USED:
//   • Id property named "Id" → EF Core recognizes it as the primary key
//   • Navigation properties marked as virtual → enables lazy loading if needed
//   • Required strings use string (not string?) — nullable reference types are enabled
//   • Nullable columns use string? / DateTime? / int? etc.
//   • [Column] attributes override EF Core's default snake_case conversion
//
// UUID GENERATION STRATEGY (spec Foundation §4.1):
//   "All tables use UUID primary keys generated by the API (not DB serial)"
//   Ids are set in the API code before inserting, using Guid.NewGuid().
//   EF Core is told NOT to use database-generated values via:
//     builder.Property(e => e.Id).ValueGeneratedNever()
//   This is configured in ApplicationDbContext.OnModelCreating().
//
// FUTURE PHASE COLUMNS (spec Foundation §4):
//   "Columns populated in later phases are nullable until that phase is deployed."
//   Phase 4 columns (stripe_customer_id, has_payment_method) are included
//   as nullable properties so the schema is complete from Day 1. This prevents
//   breaking migrations when Phase 4 ships.
// ─────────────────────────────────────────────────────────────────────────────

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;
using GolfFundraiserPro.Api.Domain.Enums;

namespace GolfFundraiserPro.Api.Domain.Entities;

// ─────────────────────────────────────────────────────────────────────────────
// ORGANIZATION
// Maps to the "organizations" table — the top-level tenant entity.
// Every event, course, and email template belongs to an organization.
// ─────────────────────────────────────────────────────────────────────────────
[Table("organizations")]
public class Organization
{
    /// <summary>
    /// UUID primary key. Generated by the API before insert (not by the database).
    /// See spec: "All tables use UUID primary keys generated by the API (not DB serial)."
    /// </summary>
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>Display name of the organization. e.g. "Clear Lake High School Boosters"</summary>
    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// URL-safe identifier. e.g. "clhs". Used in public routes: /e/{slug}/{eventCode}.
    /// Max 60 chars. Must be unique across all organizations.
    /// </summary>
    [Column("slug")]
    [MaxLength(60)]
    public string Slug { get; set; } = string.Empty;

    /// <summary>CDN URL of the org's logo image. Uploaded via POST /api/v1/orgs/{id}/logo.</summary>
    [Column("logo_url")]
    [MaxLength(500)]
    public string? LogoUrl { get; set; }

    /// <summary>
    /// 5-token color theme stored as JSONB.
    /// Stored as a JSON string and deserialized by the API.
    /// null = use ECO_GREEN_DEFAULT (handled in the theme service layer).
    /// EF Core maps this as a string column with HasColumnType("jsonb").
    /// </summary>
    [Column("theme", TypeName = "jsonb")]
    public string? ThemeJson { get; set; }

    /// <summary>The org's charitable mission statement. Displayed on donation pages.</summary>
    [Column("mission_statement")]
    [MaxLength(1000)]
    public string? MissionStatement { get; set; }

    /// <summary>
    /// If true, donation receipt emails include the IRS 501(c)3 tax deductibility notice.
    /// Spec: "Donation receipt emails: amount, event name, org name, 501c3 note if is_501c3=true."
    /// </summary>
    [Column("is_501c3")]
    public bool Is501c3 { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties
    public ICollection<Event> Events { get; set; } = new List<Event>();
    public ICollection<Course> Courses { get; set; } = new List<Course>();
    public ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();
}

// ─────────────────────────────────────────────────────────────────────────────
// EVENT
// Maps to the "events" table. The central scheduling entity.
// ─────────────────────────────────────────────────────────────────────────────
[Table("events")]
public class Event
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// 8-character random alphanumeric code. Used in QR codes and public URLs.
    /// e.g. "A3B7C9D2" → /e/clhs/A3B7C9D2
    /// Generated by the API on event creation. Indexed for fast lookup by QR scanner.
    /// </summary>
    [Column("event_code")]
    [MaxLength(8)]
    public string EventCode { get; set; } = string.Empty;

    [Column("format")]
    public EventFormat Format { get; set; }

    [Column("start_type")]
    public EventStartType StartType { get; set; }

    /// <summary>Number of holes: 9 or 18. All scoring calculations respect this value.</summary>
    [Column("holes")]
    public short Holes { get; set; } = 18;

    [Column("status")]
    public EventStatus Status { get; set; } = EventStatus.Draft;

    /// <summary>When true, a warning bar is shown across all admin event tabs.</summary>
    [Column("is_test_mode")]
    public bool IsTestMode { get; set; } = false;

    /// <summary>
    /// Scheduled round start time in UTC. Used to trigger the 24-hour reminder email.
    /// Nullable because Draft events may not have a confirmed start time yet.
    /// </summary>
    [Column("start_at")]
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Flexible JSONB settings bag: allow_walk_ups, max_teams, tee_intervals,
    /// free_agent_enabled, etc.
    /// Stored as JSON string, deserialized in the Events feature service.
    /// </summary>
    [Column("config", TypeName = "jsonb")]
    public string ConfigJson { get; set; } = "{}";

    // ── Per-event branding overrides — null = inherit from Organization ─────────

    [Column("logo_url")]
    [MaxLength(500)]
    public string? LogoUrl { get; set; }

    [Column("theme_json", TypeName = "jsonb")]
    public string? ThemeJson { get; set; }

    [Column("mission_statement")]
    [MaxLength(1000)]
    public string? MissionStatement { get; set; }

    [Column("is_501c3")]
    public bool Is501c3 { get; set; }

    // Foreign key + navigation
    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;

    public ICollection<Team> Teams { get; set; } = new List<Team>();
    public ICollection<Score> Scores { get; set; } = new List<Score>();
    public ICollection<Sponsor> Sponsors { get; set; } = new List<Sponsor>();
    public ICollection<HoleChallenge> HoleChallenges { get; set; } = new List<HoleChallenge>();
    public ICollection<Donation> Donations { get; set; } = new List<Donation>();
    public ICollection<QrCode> QrCodes { get; set; } = new List<QrCode>();

    /// <summary>
    /// The course attached to this event (set via POST /api/v1/events/{id}/course).
    /// Optional — events can be created before a course is attached.
    /// </summary>
    public Course? Course { get; set; }

    [Column("course_id")]
    public Guid? CourseId { get; set; }
}

// ─────────────────────────────────────────────────────────────────────────────
// COURSE
// Maps to the "courses" table. A golf course with per-hole metadata.
// ─────────────────────────────────────────────────────────────────────────────
[Table("courses")]
public class Course
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("address")]
    [MaxLength(300)]
    public string Address { get; set; } = string.Empty;

    [Column("city")]
    [MaxLength(100)]
    public string City { get; set; } = string.Empty;

    [Column("state")]
    [MaxLength(50)]
    public string State { get; set; } = string.Empty;

    [Column("zip")]
    [MaxLength(20)]
    public string Zip { get; set; } = string.Empty;

    /// <summary>
    /// WGS-84 lat/lon of the course clubhouse / main entrance.
    /// Type: GEOGRAPHY(Point,4326) in PostgreSQL.
    /// Requires NetTopologySuite + UseNetTopologySuite() on NpgsqlDataSource.
    /// SRID 4326 = standard GPS coordinate system.
    /// </summary>
    [Column("location", TypeName = "geography (point)")]
    public Point? Location { get; set; }

    /// <summary>Phase 5b: USGA course rating for the default tees. Required for USGA handicap differential.</summary>
    [Column("course_rating")]
    public double? CourseRating { get; set; }

    /// <summary>Phase 5b: USGA slope rating for the default tees. Required for USGA handicap differential.</summary>
    [Column("slope_rating")]
    public int? SlopeRating { get; set; }

    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;

    public ICollection<CourseHole> Holes { get; set; } = new List<CourseHole>();
}

// ─────────────────────────────────────────────────────────────────────────────
// COURSE HOLE
// Maps to the "course_holes" table. One row per hole per course (up to 18).
// ─────────────────────────────────────────────────────────────────────────────
[Table("course_holes")]
public class CourseHole
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("course_id")]
    public Guid CourseId { get; set; }

    /// <summary>Hole number 1–18 (or 1–9 for 9-hole courses).</summary>
    [Column("hole_number")]
    public short HoleNumber { get; set; }

    /// <summary>Par for this hole (3, 4, or 5).</summary>
    [Column("par")]
    public short Par { get; set; }

    /// <summary>
    /// Hole difficulty rank 1–18 (1 = hardest hole on the course).
    /// Used to allocate net strokes in match play and Phase 5 league net scoring.
    /// The hardest hole gets handicap strokes first when players have a handicap.
    /// </summary>
    [Column("handicap_index")]
    public short HandicapIndex { get; set; }

    // Yardages from different tee boxes (nullable — not all courses provide all tees)
    [Column("yardage_white")]
    public int? YardageWhite { get; set; }

    [Column("yardage_blue")]
    public int? YardageBlue { get; set; }

    [Column("yardage_red")]
    public int? YardageRed { get; set; }

    /// <summary>
    /// Phase 6: GPS location of the pin (cup) on the green.
    /// Type: GEOGRAPHY(PointZ,4326) — includes elevation (Z coordinate).
    /// NULL until Phase 6 is deployed. The column exists in the schema from Phase 1
    /// per the spec: "Columns populated in later phases are nullable."
    /// </summary>
    [Column("cup_location", TypeName = "geography (pointz)")]
    public Point? CupLocation { get; set; }

    /// <summary>Phase 6: Elevation of the cup in meters above sea level.</summary>
    [Column("cup_elevation_m")]
    public float? CupElevationM { get; set; }

    [ForeignKey(nameof(CourseId))]
    public Course Course { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// TEAM
// Maps to the "teams" table. A group of players registered for an event.
// ─────────────────────────────────────────────────────────────────────────────
[Table("teams")]
public class Team
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The player who registered the team. May be null for admin-created teams.
    /// NOT a FK to the users table — it's a FK to players in this same event.
    /// </summary>
    [Column("captain_player_id")]
    public Guid? CaptainPlayerId { get; set; }

    /// <summary>
    /// For shotgun starts: which hole number this team begins on (1–18).
    /// Set by POST /api/v1/events/{id}/shotgun-assignments.
    /// </summary>
    [Column("starting_hole")]
    public short? StartingHole { get; set; }

    /// <summary>
    /// For tee_times start type: the team's scheduled tee time in UTC.
    /// Set by POST /api/v1/events/{id}/tee-times.
    /// </summary>
    [Column("tee_time")]
    public DateTime? TeeTime { get; set; }

    /// <summary>Whether the entry fee has been collected for this team.</summary>
    [Column("entry_fee_paid")]
    public bool EntryFeePaid { get; set; }

    /// <summary>
    /// Signed HMAC token for the team invite link.
    /// Format: base64url(HMAC-SHA256(teamId + expires_at, JWT_SECRET))
    /// Expires after 48 hours (invite_expires_at).
    /// </summary>
    [Column("invite_token")]
    [MaxLength(128)]
    public string? InviteToken { get; set; }

    [Column("invite_expires_at")]
    public DateTime? InviteExpiresAt { get; set; }

    /// <summary>Maximum number of players allowed on this team. Default: 4.</summary>
    [Column("max_players")]
    public short MaxPlayers { get; set; } = 4;

    [Column("check_in_status")]
    public CheckInStatus CheckInStatus { get; set; } = CheckInStatus.Pending;

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    public ICollection<Player> Players { get; set; } = new List<Player>();
    public ICollection<Score> Scores { get; set; } = new List<Score>();
}

// ─────────────────────────────────────────────────────────────────────────────
// PLAYER
// Maps to the "players" table. An individual golfer registered for an event.
// Note: a player is event-scoped (not a global user account).
//       The organizer has a user account (ASP.NET Identity); golfers do not.
// ─────────────────────────────────────────────────────────────────────────────
[Table("players")]
public class Player
{
    [Column("id")]
    public Guid Id { get; set; }

    /// <summary>
    /// The team this player belongs to.
    /// Nullable because free agents are in the DB before being assigned a team.
    /// </summary>
    [Column("team_id")]
    public Guid? TeamId { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("first_name")]
    [MaxLength(100)]
    public string FirstName { get; set; } = string.Empty;

    [Column("last_name")]
    [MaxLength(100)]
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Email is unique per event (a person can't register twice for the same event).
    /// The DB has a UNIQUE constraint on (event_id, email).
    /// This is configured in ApplicationDbContext.OnModelCreating().
    /// </summary>
    [Column("email")]
    [MaxLength(254)]
    public string Email { get; set; } = string.Empty;

    [Column("phone")]
    [MaxLength(30)]
    public string? Phone { get; set; }

    /// <summary>
    /// Golf handicap index (USGA format). e.g. 14.2 means 14.2 handicap.
    /// Used by Phase 5 league net scoring and the free agent auto-pair algorithm.
    /// Nullable because most charity event golfers don't have official handicaps.
    /// </summary>
    [Column("handicap_index")]
    public double? HandicapIndex { get; set; }

    [Column("registration_type")]
    public RegistrationType RegistrationType { get; set; }

    /// <summary>Self-reported for free agent pool matching. Nullable.</summary>
    [Column("skill_level")]
    public SkillLevel? SkillLevel { get; set; }

    /// <summary>Self-reported for free agent pool matching. Nullable.</summary>
    [Column("age_group")]
    public AgeGroup? AgeGroup { get; set; }

    /// <summary>
    /// Free-text pairing note from the player during free agent registration.
    /// e.g. "I know the Smith family, please pair me with them if possible."
    /// The organizer sees this on the Free Agent Board.
    /// </summary>
    [Column("pairing_note")]
    [MaxLength(500)]
    public string? PairingNote { get; set; }

    [Column("check_in_status")]
    public CheckInStatus CheckInStatus { get; set; } = CheckInStatus.Pending;

    [Column("check_in_at")]
    public DateTime? CheckInAt { get; set; }

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    // ── Phase 4 columns ──────────────────────────────────────────────────────
    // These columns exist in the schema from Phase 1 (nullable) but are only
    // populated once Phase 4 (Stripe payments) is deployed.

    /// <summary>
    /// Phase 4: true once the player has saved a card via Stripe SetupIntent.
    /// Controls whether auction bidding is available to this player.
    /// </summary>
    [Column("has_payment_method")]
    public bool HasPaymentMethod { get; set; } = false;

    /// <summary>
    /// Phase 4: Stripe Customer ID (cus_...) for this player.
    /// Stored here as a denormalized lookup; canonical record is stripe_customers table.
    /// </summary>
    [Column("stripe_customer_id")]
    [MaxLength(50)]
    public string? StripeCustomerId { get; set; }

    /// <summary>
    /// Phase 3: Expo push notification token registered from the mobile app.
    /// Null = player has not granted permission or has opted out.
    /// </summary>
    [Column("expo_push_token")]
    [MaxLength(500)]
    public string? ExpoPushToken { get; set; }

    // Navigation
    [ForeignKey(nameof(TeamId))]
    public Team? Team { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// SCORE
// Maps to the "scores" table. One row per hole per team.
// The leaderboard is computed by aggregating these rows.
// ─────────────────────────────────────────────────────────────────────────────
[Table("scores")]
public class Score
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("team_id")]
    public Guid TeamId { get; set; }

    /// <summary>Which hole (1–18) this score is for.</summary>
    [Column("hole_number")]
    public short HoleNumber { get; set; }

    /// <summary>
    /// Total strokes for this team on this hole (gross score).
    /// In scramble format, this is the team's collective score.
    /// In stroke/best_ball, this is the relevant individual score.
    /// </summary>
    [Column("gross_score")]
    public short GrossScore { get; set; }

    /// <summary>Number of putts on the green. Optional — used for putting challenges.</summary>
    [Column("putts")]
    public short? Putts { get; set; }

    /// <summary>
    /// Phase 2: Per-player shot breakdown. Stored as JSONB.
    /// e.g. { "player-uuid-1": 4, "player-uuid-2": 5 }
    /// Null in Phase 1 (admin entry doesn't record individual shots).
    /// </summary>
    [Column("player_shots", TypeName = "jsonb")]
    public string? PlayerShotsJson { get; set; }

    /// <summary>
    /// The device that submitted this score. Used for conflict detection.
    /// If two different device IDs submit different scores for the same hole,
    /// is_conflicted is set to true and the admin must resolve it.
    /// </summary>
    [Column("device_id")]
    [MaxLength(100)]
    public string DeviceId { get; set; } = string.Empty;

    [Column("submitted_at")]
    public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this score was synced from the mobile device to the server.
    /// Null for scores entered directly on the admin dashboard (no sync needed).
    /// </summary>
    [Column("synced_at")]
    public DateTime? SyncedAt { get; set; }

    [Column("source")]
    public ScoreSource Source { get; set; }

    /// <summary>
    /// True if two devices submitted conflicting scores for this hole.
    /// The admin dashboard shows a conflict resolution UI when this is true.
    /// </summary>
    [Column("is_conflicted")]
    public bool IsConflicted { get; set; } = false;

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    // ── Phase 6 GPS columns ──────────────────────────────────────────────────
    /// <summary>Phase 6: GPS location where the team's drive landed.</summary>
    [Column("drive_location", TypeName = "geography (point)")]
    public Point? DriveLocation { get; set; }

    /// <summary>Phase 6: GPS location of the ball when it came to rest.</summary>
    [Column("ball_location", TypeName = "geography (point)")]
    public Point? BallLocation { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    [ForeignKey(nameof(TeamId))]
    public Team Team { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// SPONSOR
// Maps to the "sponsors" table. Sponsors are attached to events.
// ─────────────────────────────────────────────────────────────────────────────
[Table("sponsors")]
public class Sponsor
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("logo_url")]
    [MaxLength(500)]
    public string LogoUrl { get; set; } = string.Empty;

    [Column("website_url")]
    [MaxLength(500)]
    public string? WebsiteUrl { get; set; }

    [Column("tagline")]
    [MaxLength(200)]
    public string? Tagline { get; set; }

    [Column("tier")]
    public SponsorTier Tier { get; set; }

    /// <summary>Sponsor's committed donation to the event, in US cents. Rolls into fundraising totals.</summary>
    [Column("donation_amount_cents")]
    public int? DonationAmountCents { get; set; }

    /// <summary>
    /// JSONB placement configuration. e.g.:
    /// { "leaderboard": true, "landingPage": true, "holeNumbers": [7, 14] }
    /// The Sponsors feature service deserializes this to a typed object.
    /// </summary>
    [Column("placements", TypeName = "jsonb")]
    public string PlacementsJson { get; set; } = "{}";

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// HOLE CHALLENGE
// Maps to the "hole_challenges" table. On-course contests.
// ─────────────────────────────────────────────────────────────────────────────
[Table("hole_challenges")]
public class HoleChallenge
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    /// <summary>
    /// Which hole this challenge is on. NULL = all-day challenge (e.g. hole-in-one
    /// on any hole throughout the round).
    /// </summary>
    [Column("hole_number")]
    public short? HoleNumber { get; set; }

    [Column("challenge_type")]
    public ChallengeType ChallengeType { get; set; }

    [Column("description")]
    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    [Column("prize_description")]
    [MaxLength(500)]
    public string? PrizeDescription { get; set; }

    /// <summary>Optional: the sponsor funding this challenge's prize.</summary>
    [Column("sponsor_id")]
    public Guid? SponsorId { get; set; }

    [Column("sponsor_name")]
    [MaxLength(200)]
    public string? SponsorName { get; set; }

    [Column("sponsor_logo_url")]
    [MaxLength(500)]
    public string? SponsorLogoUrl { get; set; }

    /// <summary>Prize or donation amount for this challenge, in US cents. Rolls into fundraising totals.</summary>
    [Column("donation_amount_cents")]
    public int? DonationAmountCents { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    [ForeignKey(nameof(SponsorId))]
    public Sponsor? Sponsor { get; set; }

    public ICollection<ChallengeResult> Results { get; set; } = new List<ChallengeResult>();
}

// ─────────────────────────────────────────────────────────────────────────────
// CHALLENGE RESULT
// Maps to the "challenge_results" table. Admin records results here.
// ─────────────────────────────────────────────────────────────────────────────
[Table("challenge_results")]
public class ChallengeResult
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("challenge_id")]
    public Guid ChallengeId { get; set; }

    [Column("team_id")]
    public Guid TeamId { get; set; }

    /// <summary>Which player on the team achieved this result (optional for team challenges).</summary>
    [Column("player_id")]
    public Guid? PlayerId { get; set; }

    /// <summary>
    /// Numeric result value. Semantics depend on challenge_type:
    ///   closest_to_pin / longest_drive → distance in yards (lower/higher wins respectively)
    ///   putting → number of putts (lower wins)
    ///   Phase 6: GPS-measured distance replaces manual entry
    /// </summary>
    [Column("result_value")]
    public float? ResultValue { get; set; }

    [Column("result_notes")]
    [MaxLength(500)]
    public string? ResultNotes { get; set; }

    [Column("recorded_at")]
    public DateTime RecordedAt { get; set; } = DateTime.UtcNow;

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [ForeignKey(nameof(ChallengeId))]
    public HoleChallenge Challenge { get; set; } = null!;

    [ForeignKey(nameof(TeamId))]
    public Team Team { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// DONATION
// Maps to the "donations" table.
// ─────────────────────────────────────────────────────────────────────────────
[Table("donations")]
public class Donation
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("donor_name")]
    [MaxLength(200)]
    public string DonorName { get; set; } = string.Empty;

    [Column("donor_email")]
    [MaxLength(254)]
    public string DonorEmail { get; set; } = string.Empty;

    /// <summary>
    /// Amount in US cents (integer) to avoid floating-point currency errors.
    /// e.g. $50.00 is stored as 5000.
    /// All money values in the system follow this convention.
    /// </summary>
    [Column("amount_cents")]
    public int AmountCents { get; set; }

    /// <summary>Whether a donation receipt email has been sent to this donor.</summary>
    [Column("receipt_sent")]
    public bool ReceiptSent { get; set; } = false;

    /// <summary>
    /// Phase 4: Stripe PaymentIntent ID for online donations processed via the donation widget.
    /// Null for Phase 1 (donations are recorded manually by the organizer).
    /// </summary>
    [Column("stripe_payment_intent_id")]
    [MaxLength(100)]
    public string? StripePaymentIntentId { get; set; }

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// EMAIL TEMPLATE
// Maps to the "email_templates" table.
// Templates are org-branded and stored in the database (not as static files).
// This allows organizers to customise email copy in the admin dashboard.
// ─────────────────────────────────────────────────────────────────────────────
[Table("email_templates")]
public class EmailTemplate
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("trigger_type")]
    public EmailTriggerType TriggerType { get; set; }

    [Column("subject")]
    [MaxLength(200)]
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Full HTML email body with theme placeholders like {{PRIMARY_COLOR}}.
    /// At send time, buildEmailVars() from @gfp/theme substitutes the org's
    /// actual hex values. The QR code and player-specific data are injected
    /// by the Email feature service at send time.
    /// </summary>
    [Column("html_body")]
    public string HtmlBody { get; set; } = string.Empty;

    /// <summary>
    /// If false, this template is disabled — the trigger fires but no email is sent.
    /// Allows orgs to opt out of specific automated emails (e.g. disable reminder emails).
    /// </summary>
    [Column("is_active")]
    public bool IsActive { get; set; } = true;

    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// STRIPE CUSTOMER
// Maps to "stripe_customers" — one row per player who has saved a card.
// The canonical Stripe customer/payment_method record; Player.StripeCustomerId
// is a denormalized FK for fast lookup.
// ─────────────────────────────────────────────────────────────────────────────
[Table("stripe_customers")]
public class StripeCustomer
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("player_id")]
    public Guid PlayerId { get; set; }

    /// <summary>Stripe Customer ID (cus_...). Created once per player.</summary>
    [Column("stripe_customer_id")]
    [MaxLength(50)]
    public string StripeCustomerId { get; set; } = string.Empty;

    /// <summary>Stripe PaymentMethod ID (pm_...). The default saved card.</summary>
    [Column("stripe_payment_method_id")]
    [MaxLength(50)]
    public string StripePaymentMethodId { get; set; } = string.Empty;

    /// <summary>Card brand displayed in the UI (e.g. "visa", "mastercard").</summary>
    [Column("card_brand")]
    [MaxLength(20)]
    public string? CardBrand { get; set; }

    /// <summary>Last 4 digits of the saved card for display purposes.</summary>
    [Column("card_last4")]
    [MaxLength(4)]
    public string? CardLast4 { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(PlayerId))]
    public Player Player { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// AUCTION ITEM
// Maps to "auction_items" — one row per item for any auction format.
// ─────────────────────────────────────────────────────────────────────────────
[Table("auction_items")]
public class AuctionItem
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("title")]
    [MaxLength(200)]
    public string Title { get; set; } = string.Empty;

    [Column("description")]
    [MaxLength(2000)]
    public string Description { get; set; } = string.Empty;

    /// <summary>JSONB array of photo URLs uploaded to CDN.</summary>
    [Column("photo_urls", TypeName = "jsonb")]
    public string PhotoUrlsJson { get; set; } = "[]";

    [Column("auction_type")]
    public AuctionType AuctionType { get; set; }

    [Column("status")]
    public AuctionItemStatus Status { get; set; } = AuctionItemStatus.Open;

    /// <summary>Starting bid amount in cents.</summary>
    [Column("starting_bid_cents")]
    public int StartingBidCents { get; set; }

    /// <summary>Minimum increment over the current high bid in cents.</summary>
    [Column("bid_increment_cents")]
    public int BidIncrementCents { get; set; } = 500;

    /// <summary>If set and a bid reaches this amount, item closes immediately (buy-now).</summary>
    [Column("buy_now_price_cents")]
    public int? BuyNowPriceCents { get; set; }

    /// <summary>Current highest bid in cents. Denormalized for fast display.</summary>
    [Column("current_high_bid_cents")]
    public int CurrentHighBidCents { get; set; }

    /// <summary>When this item's silent auction closes.</summary>
    [Column("closes_at")]
    public DateTime? ClosesAt { get; set; }

    /// <summary>Original scheduled close time. Used to compute max_extension_min ceiling.</summary>
    [Column("original_closes_at")]
    public DateTime? OriginalClosesAt { get; set; }

    /// <summary>Maximum minutes the close time can be extended via bid-extension rule.</summary>
    [Column("max_extension_min")]
    public int MaxExtensionMin { get; set; } = 10;

    /// <summary>Display order on the auction screen.</summary>
    [Column("display_order")]
    public int DisplayOrder { get; set; }

    // Donation-item fields
    /// <summary>JSONB array of fixed pledge denominations in cents, or null for open amount.</summary>
    [Column("donation_denominations", TypeName = "jsonb")]
    public string? DonationDenominationsJson { get; set; }

    /// <summary>Minimum bid/pledge in cents (for open-amount donation items).</summary>
    [Column("minimum_bid_cents")]
    public int? MinimumBidCents { get; set; }

    /// <summary>Fair-market value in cents. Used for tax receipt deductible calculation.</summary>
    [Column("fair_market_value_cents")]
    public int FairMarketValueCents { get; set; }

    /// <summary>Fundraising goal in cents for the goal thermometer display.</summary>
    [Column("goal_cents")]
    public int? GoalCents { get; set; }

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    public ICollection<Bid> Bids { get; set; } = new List<Bid>();
    public ICollection<AuctionWinner> Winners { get; set; } = new List<AuctionWinner>();
}

// ─────────────────────────────────────────────────────────────────────────────
// BID
// Maps to "bids" — one row per bid (or pledge for donation items).
// ─────────────────────────────────────────────────────────────────────────────
[Table("bids")]
public class Bid
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("auction_item_id")]
    public Guid AuctionItemId { get; set; }

    [Column("player_id")]
    public Guid PlayerId { get; set; }

    [Column("amount_cents")]
    public int AmountCents { get; set; }

    [Column("placed_at")]
    public DateTime PlacedAt { get; set; } = DateTime.UtcNow;

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [ForeignKey(nameof(AuctionItemId))]
    public AuctionItem AuctionItem { get; set; } = null!;

    [ForeignKey(nameof(PlayerId))]
    public Player Player { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// AUCTION WINNER
// Maps to "auction_winners" — one row per winner per item.
// Silent/live items: one row. Donation items: one row per pledger.
// ─────────────────────────────────────────────────────────────────────────────
[Table("auction_winners")]
public class AuctionWinner
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("auction_item_id")]
    public Guid AuctionItemId { get; set; }

    [Column("player_id")]
    public Guid PlayerId { get; set; }

    [Column("amount_cents")]
    public int AmountCents { get; set; }

    [Column("charge_status")]
    public ChargeStatus ChargeStatus { get; set; } = ChargeStatus.Pending;

    /// <summary>Stripe PaymentIntent ID (pi_...) for this winner's charge.</summary>
    [Column("stripe_payment_intent_id")]
    [MaxLength(100)]
    public string? StripePaymentIntentId { get; set; }

    [Column("receipt_sent")]
    public bool ReceiptSent { get; set; } = false;

    /// <summary>True for admin-generated test data; cleared when moving to Active.</summary>
    [Column("is_test")]
    public bool IsTest { get; set; } = false;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(AuctionItemId))]
    public AuctionItem AuctionItem { get; set; } = null!;

    [ForeignKey(nameof(PlayerId))]
    public Player Player { get; set; } = null!;
}

// ─────────────────────────────────────────────────────────────────────────────
// AUCTION SESSION
// Maps to "auction_sessions" — tracks a live auction session.
// One session per live auction run for an event.
// ─────────────────────────────────────────────────────────────────────────────
[Table("auction_sessions")]
public class AuctionSession
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    /// <summary>True while the live auction is in progress. False once ended.</summary>
    [Column("is_active")]
    public bool IsActive { get; set; } = true;

    /// <summary>The auction_item currently being called by the host.</summary>
    [Column("current_item_id")]
    public Guid? CurrentItemId { get; set; }

    /// <summary>The amount currently being called by the host (in cents).</summary>
    [Column("current_called_amount_cents")]
    public int CurrentCalledAmountCents { get; set; }

    /// <summary>Live count of attendees who pressed "I'm Bidding" for the current item. Resets to 0 when the item advances.</summary>
    [Column("current_bidder_count")]
    public int CurrentBidderCount { get; set; }

    [Column("started_at")]
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;

    [Column("ended_at")]
    public DateTime? EndedAt { get; set; }

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;

    [ForeignKey(nameof(CurrentItemId))]
    public AuctionItem? CurrentItem { get; set; }
}

// ─────────────────────────────────────────────────────────────────────────────
// PHASE 5: LEAGUE PLAY + HANDICAPS
// ─────────────────────────────────────────────────────────────────────────────

// ── LEAGUE ────────────────────────────────────────────────────────────────────
[Table("leagues")]
public class League
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("org_id")]
    public Guid OrgId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("format")]
    public LeagueFormat Format { get; set; }

    [Column("handicap_system")]
    public HandicapSystem HandicapSystem { get; set; } = HandicapSystem.Club;

    /// <summary>JSONB formula config. e.g. { "type": "BestNofM", "n": 5, "m": 10 }</summary>
    [Column("handicap_formula", TypeName = "jsonb")]
    public string HandicapFormulaJson { get; set; } = "{\"type\":\"BestNofM\",\"n\":5,\"m\":10}";

    /// <summary>Maximum allowed handicap index. Any calculated value above this is capped.</summary>
    [Column("handicap_cap")]
    public double HandicapCap { get; set; } = 36.0;

    /// <summary>Max number of player skill flights per season.</summary>
    [Column("max_flights")]
    public short MaxFlights { get; set; } = 1;

    /// <summary>League dues in cents. 0 = no dues.</summary>
    [Column("dues_cents")]
    public int DuesCents { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(OrgId))]
    public Organization Organization { get; set; } = null!;

    public ICollection<Season> Seasons { get; set; } = new List<Season>();
}

// ── SEASON ────────────────────────────────────────────────────────────────────
[Table("seasons")]
public class Season
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("league_id")]
    public Guid LeagueId { get; set; }

    [Column("name")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Column("total_rounds")]
    public short TotalRounds { get; set; }

    [Column("start_date")]
    public DateOnly StartDate { get; set; }

    [Column("end_date")]
    public DateOnly EndDate { get; set; }

    /// <summary>Status mirrors EventStatus pattern: Draft / Active / Completed.</summary>
    [Column("status")]
    [MaxLength(50)]
    public string Status { get; set; } = "Draft";

    /// <summary>
    /// How many rounds count toward standings. 0 = all rounds.
    /// e.g. 10 = best 10 of total_rounds (lowest net or highest Stableford).
    /// </summary>
    [Column("rounds_counted")]
    public short RoundsCounted { get; set; }

    /// <summary>
    /// Stroke play standing method: "TotalNet" or "AverageNet".
    /// Only relevant when Format = Stroke.
    /// </summary>
    [Column("standing_method")]
    [MaxLength(50)]
    public string StandingMethod { get; set; } = "TotalNet";

    /// <summary>
    /// Phase 5b: when true, league handicap recalculation writes the updated index
    /// back to players.handicap_index (tournament handicap). Admin-controlled toggle.
    /// </summary>
    [Column("sync_handicap_to_player")]
    public bool SyncHandicapToPlayer { get; set; } = false;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(LeagueId))]
    public League League { get; set; } = null!;

    public ICollection<Flight> Flights { get; set; } = new List<Flight>();
    public ICollection<LeagueMember> Members { get; set; } = new List<LeagueMember>();
    public ICollection<LeagueRound> Rounds { get; set; } = new List<LeagueRound>();
    public ICollection<Standing> Standings { get; set; } = new List<Standing>();
}

// ── FLIGHT ────────────────────────────────────────────────────────────────────
[Table("flights")]
public class Flight
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("season_id")]
    public Guid SeasonId { get; set; }

    [Column("name")]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>Lower bound of handicap range for this flight (inclusive). Null = no lower bound.</summary>
    [Column("min_handicap")]
    public double? MinHandicap { get; set; }

    /// <summary>Upper bound of handicap range for this flight (inclusive). Null = no upper bound.</summary>
    [Column("max_handicap")]
    public double? MaxHandicap { get; set; }

    [ForeignKey(nameof(SeasonId))]
    public Season Season { get; set; } = null!;

    public ICollection<LeagueMember> Members { get; set; } = new List<LeagueMember>();
}

// ── LEAGUE MEMBER ─────────────────────────────────────────────────────────────
[Table("league_members")]
public class LeagueMember
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("season_id")]
    public Guid SeasonId { get; set; }

    /// <summary>Optional link to an event-scoped Player record. Null for walk-in subs.</summary>
    [Column("player_id")]
    public Guid? PlayerId { get; set; }

    [Column("flight_id")]
    public Guid? FlightId { get; set; }

    [Column("first_name")]
    [MaxLength(100)]
    public string FirstName { get; set; } = string.Empty;

    [Column("last_name")]
    [MaxLength(100)]
    public string LastName { get; set; } = string.Empty;

    [Column("email")]
    [MaxLength(254)]
    public string Email { get; set; } = string.Empty;

    [Column("handicap_index")]
    public double HandicapIndex { get; set; }

    [Column("dues_paid")]
    public bool DuesPaid { get; set; }

    [Column("rounds_played")]
    public short RoundsPlayed { get; set; }

    [Column("absences")]
    public short Absences { get; set; }

    [Column("status")]
    public MemberStatus Status { get; set; } = MemberStatus.Active;

    [Column("joined_at")]
    public DateTime JoinedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(SeasonId))]
    public Season Season { get; set; } = null!;

    [ForeignKey(nameof(FlightId))]
    public Flight? Flight { get; set; }

    public ICollection<HandicapHistory> HandicapHistories { get; set; } = new List<HandicapHistory>();
    public ICollection<LeagueScore> Scores { get; set; } = new List<LeagueScore>();
}

// ── LEAGUE ROUND ──────────────────────────────────────────────────────────────
[Table("league_rounds")]
public class LeagueRound
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("season_id")]
    public Guid SeasonId { get; set; }

    [Column("course_id")]
    public Guid? CourseId { get; set; }

    [Column("round_date")]
    public DateOnly RoundDate { get; set; }

    [Column("status")]
    public RoundStatus Status { get; set; } = RoundStatus.Scheduled;

    [Column("notes")]
    [MaxLength(500)]
    public string? Notes { get; set; }

    [ForeignKey(nameof(SeasonId))]
    public Season Season { get; set; } = null!;

    [ForeignKey(nameof(CourseId))]
    public Course? Course { get; set; }

    public ICollection<LeaguePairing> Pairings { get; set; } = new List<LeaguePairing>();
    public ICollection<LeagueScore> Scores { get; set; } = new List<LeagueScore>();
    public ICollection<Skin> Skins { get; set; } = new List<Skin>();
    public ICollection<RoundAbsence> Absences { get; set; } = new List<RoundAbsence>();
}

// ── LEAGUE PAIRING ────────────────────────────────────────────────────────────
[Table("league_pairings")]
public class LeaguePairing
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("round_id")]
    public Guid RoundId { get; set; }

    [Column("group_number")]
    public short GroupNumber { get; set; }

    /// <summary>JSONB array of LeagueMember IDs in this group.</summary>
    [Column("member_ids", TypeName = "jsonb")]
    public string MemberIdsJson { get; set; } = "[]";

    [Column("tee_time")]
    public TimeOnly? TeeTime { get; set; }

    [Column("starting_hole")]
    public short? StartingHole { get; set; }

    /// <summary>True once the admin has locked pairings and notified players.</summary>
    [Column("is_locked")]
    public bool IsLocked { get; set; }

    [ForeignKey(nameof(RoundId))]
    public LeagueRound Round { get; set; } = null!;
}

// ── LEAGUE SCORE ──────────────────────────────────────────────────────────────
[Table("league_scores")]
public class LeagueScore
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("round_id")]
    public Guid RoundId { get; set; }

    [Column("member_id")]
    public Guid MemberId { get; set; }

    [Column("hole_number")]
    public short HoleNumber { get; set; }

    [Column("gross_score")]
    public short GrossScore { get; set; }

    /// <summary>Net score = gross − handicap strokes allocated to this hole.</summary>
    [Column("net_score")]
    public short NetScore { get; set; }

    /// <summary>Stableford points: max(0, 2 + par − net_score).</summary>
    [Column("stableford_points")]
    public short StablefordPoints { get; set; }

    [ForeignKey(nameof(RoundId))]
    public LeagueRound Round { get; set; } = null!;

    [ForeignKey(nameof(MemberId))]
    public LeagueMember Member { get; set; } = null!;
}

// ── HANDICAP HISTORY ──────────────────────────────────────────────────────────
[Table("handicap_history")]
public class HandicapHistory
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("member_id")]
    public Guid MemberId { get; set; }

    /// <summary>Null for manual overrides not tied to a specific round.</summary>
    [Column("round_id")]
    public Guid? RoundId { get; set; }

    [Column("old_index")]
    public double OldIndex { get; set; }

    [Column("new_index")]
    public double NewIndex { get; set; }

    /// <summary>The differential that triggered this recalculation.</summary>
    [Column("differential")]
    public double Differential { get; set; }

    /// <summary>True when an admin manually set the handicap (not engine-calculated).</summary>
    [Column("admin_override")]
    public bool AdminOverride { get; set; }

    [Column("reason")]
    [MaxLength(500)]
    public string? Reason { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(MemberId))]
    public LeagueMember Member { get; set; } = null!;

    [ForeignKey(nameof(RoundId))]
    public LeagueRound? Round { get; set; }
}

// ── STANDING ──────────────────────────────────────────────────────────────────
[Table("standings")]
public class Standing
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("season_id")]
    public Guid SeasonId { get; set; }

    [Column("flight_id")]
    public Guid? FlightId { get; set; }

    [Column("member_id")]
    public Guid MemberId { get; set; }

    /// <summary>Season Stableford points total.</summary>
    [Column("total_points")]
    public int TotalPoints { get; set; }

    /// <summary>Season net strokes total (stroke play).</summary>
    [Column("net_strokes")]
    public int NetStrokes { get; set; }

    /// <summary>Season average net score (stroke play, AverageNet method).</summary>
    [Column("season_avg_net")]
    public double SeasonAvgNet { get; set; }

    [Column("rounds_played")]
    public short RoundsPlayed { get; set; }

    /// <summary>Current rank within the flight (1 = leader). Recalculated on round close.</summary>
    [Column("rank")]
    public short Rank { get; set; }

    /// <summary>Phase 5b: total match play rounds won (match format only).</summary>
    [Column("match_wins")]
    public int MatchWins { get; set; }

    /// <summary>Phase 5b: total match play rounds lost (match format only).</summary>
    [Column("match_losses")]
    public int MatchLosses { get; set; }

    /// <summary>Phase 5b: total match play rounds halved (match format only).</summary>
    [Column("match_halves")]
    public int MatchHalves { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(SeasonId))]
    public Season Season { get; set; } = null!;

    [ForeignKey(nameof(MemberId))]
    public LeagueMember Member { get; set; } = null!;

    [ForeignKey(nameof(FlightId))]
    public Flight? Flight { get; set; }
}

// ── SKIN ──────────────────────────────────────────────────────────────────────
[Table("skins")]
public class Skin
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("round_id")]
    public Guid RoundId { get; set; }

    [Column("hole_number")]
    public short HoleNumber { get; set; }

    /// <summary>Null if this hole tied (skin carried to next hole).</summary>
    [Column("winner_member_id")]
    public Guid? WinnerMemberId { get; set; }

    [Column("pot_cents")]
    public int PotCents { get; set; }

    /// <summary>If this skin was carried over from a previous hole, that hole number. Null if won cleanly.</summary>
    [Column("carried_over_from_hole")]
    public short? CarriedOverFromHole { get; set; }

    [ForeignKey(nameof(RoundId))]
    public LeagueRound Round { get; set; } = null!;

    [ForeignKey(nameof(WinnerMemberId))]
    public LeagueMember? Winner { get; set; }
}

// ── ROUND ABSENCE ─────────────────────────────────────────────────────────────
[Table("round_absences")]
public class RoundAbsence
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("round_id")]
    public Guid RoundId { get; set; }

    /// <summary>The member who is absent from this round.</summary>
    [Column("member_id")]
    public Guid MemberId { get; set; }

    /// <summary>The substitute member assigned to fill in, if any.</summary>
    [Column("sub_member_id")]
    public Guid? SubMemberId { get; set; }

    [Column("reported_at")]
    public DateTime ReportedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(RoundId))]
    public LeagueRound Round { get; set; } = null!;

    [ForeignKey(nameof(MemberId))]
    public LeagueMember Member { get; set; } = null!;

    [ForeignKey(nameof(SubMemberId))]
    public LeagueMember? Sub { get; set; }
}

// ─────────────────────────────────────────────────────────────────────────────
// QR CODE
// Maps to the "qr_codes" table.
// Pre-generated QR codes for an event (included in the Print Kit PDF).
// ─────────────────────────────────────────────────────────────────────────────
[Table("qr_codes")]
public class QrCode
{
    [Column("id")]
    public Guid Id { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("qr_type")]
    public QrType QrType { get; set; }

    /// <summary>
    /// Signed token encoded in the QR. Format depends on qr_type:
    ///   player_checkin → HMAC-signed JSON { type, player_id, event_id }
    ///   event_join     → just the event_code (public, no signature needed)
    ///   donation        → just the event_code
    /// Max 128 chars — QR codes degrade in density above this.
    /// </summary>
    [Column("token")]
    [MaxLength(128)]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// SVG string of the rendered QR code image.
    /// Stored in the DB so the Print Kit PDF can be generated without
    /// re-rendering QR codes on every download.
    /// </summary>
    [Column("svg_data")]
    public string SvgData { get; set; } = string.Empty;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [ForeignKey(nameof(EventId))]
    public Event Event { get; set; } = null!;
}
